CREATE TABLE IF NOT EXISTS USERS
(
    ID         TEXT PRIMARY KEY,
    FIRST_NAME TEXT,
    LAST_NAME  TEXT,
    EMAIL      TEXT,
    PASSWORD   TEXT,
    TYPE       TEXT,
    CREATED_BY TEXT,
    UPDATED_BY TEXT,
    CREATED_ON DATE,
    UPDATED_ON DATE
);

CREATE TABLE IF NOT EXISTS EVENTS
(
    ID          TEXT PRIMARY KEY,
    TYPE        TEXT,
    DETAILS     TEXT,
    USER_ID     TEXT REFERENCES users(id),
    CREATED_ON  DATE
);

CREATE TABLE IF NOT EXISTS CLASSES
(
    ID          TEXT PRIMARY KEY,
    DESCRIPTION TEXT,
    PROF_ID     TEXT REFERENCES USERS (ID),
    GA_ID       TEXT REFERENCES USERS (ID),
    CREATED_BY  TEXT,
    UPDATED_BY  TEXT,
    CREATED_ON  DATE,
    UPDATED_ON  DATE
);

CREATE TABLE IF NOT EXISTS CLASS_STUDENTS
(
    ID         TEXT PRIMARY KEY,
    STUDENT_ID TEXT REFERENCES USERS (ID),
    CLASS_ID   TEXT REFERENCES CLASSES (ID),
    CREATED_BY TEXT,
    UPDATED_BY TEXT,
    CREATED_ON DATE,
    UPDATED_ON DATE,
    UNIQUE (STUDENT_ID, CLASS_ID)
);

CREATE TABLE IF NOT EXISTS ASSIGNMENTS
(
    ID           TEXT PRIMARY KEY,
    CLASS_ID     TEXT REFERENCES CLASSES (ID) NOT NULL,
    QUESTION     TEXT                         NOT NULL,
    NO_OF_GROUPS INT,
    CREATED_BY   TEXT,
    UPDATED_BY   TEXT,
    CREATED_ON   DATE,
    UPDATED_ON   DATE
);

CREATE TABLE IF NOT EXISTS GROUPS
(
    ID            TEXT PRIMARY KEY,
    GROUP_ID      TEXT NOT NULL,
    ASSIGNMENT_ID TEXT NOT NULL REFERENCES ASSIGNMENTS (ID),
    ANSWER        TEXT,
    ACTIVE        BOOLEAN,
    CREATED_BY    TEXT,
    UPDATED_BY    TEXT,
    CREATED_ON    DATE,
    UPDATED_ON    DATE,
    UNIQUE (ASSIGNMENT_ID, GROUP_ID)
);

CREATE TABLE IF NOT EXISTS GROUP_STUDENTS
(
    ID         TEXT PRIMARY KEY,
    GROUP_ID   TEXT REFERENCES GROUPS (ID) NOT NULL,
    STUDENT_ID TEXT REFERENCES USERS (ID)  NOT NULL,
    CREATED_BY TEXT,
    UPDATED_BY TEXT,
    CREATED_ON DATE,
    UPDATED_ON DATE,
    UNIQUE (STUDENT_ID, GROUP_ID)
);

CREATE TABLE IF NOT EXISTS GROUP_DISCUSSIONS
(
    ID         TEXT PRIMARY KEY,
    GROUP_ID   TEXT REFERENCES GROUPS (ID) NOT NULL,
    CHAT       TEXT                        NOT NULL,
    CREATED_BY TEXT                        NOT NULL,
    CREATED_ON DATE                        NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSIGNMENT_ANSWER
(
    ID               TEXT PRIMARY KEY,
    GROUP_ID         TEXT REFERENCES GROUPS (ID) NOT NULL,
    ANSWER           TEXT                        NOT NULL,
    STUDENT_APPROVED BOOLEAN,
    GA_APPROVED      BOOLEAN,
    CREATED_BY       TEXT                        NOT NULL,
    CREATED_ON       DATE                        NOT NULL
);

CREATE TABLE IF NOT EXISTS STUDENT_APPROVED_ANSWER
(
    ID         TEXT PRIMARY KEY,
    ANSWER     TEXT REFERENCES ASSIGNMENT_ANSWER (ID) NOT NULL,
    STUDENT_ID TEXT REFERENCES USERS (ID)             NOT NULL,
    ACCEPTED   BOOLEAN                                NOT NULL,
    CREATED_ON DATE                                   NOT NULL
);

CREATE TABLE IF NOT EXISTS GA_APPROVED_ANSWER
(
    ID         TEXT PRIMARY KEY,
    ANSWER     TEXT REFERENCES ASSIGNMENT_ANSWER (ID) NOT NULL,
    GA_ID      TEXT REFERENCES USERS (ID)             NOT NULL,
    ACCEPTED   BOOLEAN                                NOT NULL,
    CREATED_ON DATE                                   NOT NULL
);